- hosts: all
  tags: always
  become: true
  pre_tasks:
    - name: Pre-task | Update package cache
      tags: always
      apt:
        update_cache: true
        cache_valid_time: 3600
      changed_when: false

- hosts: all
  tags: base
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python
    user: marc
    python_version: "3.12.8"
    git_username: Marc Hauser
    git_email: marc.hauser@novasense.ch
  roles:
    - base
