- hosts: all
  tags: always
  become: true
  pre_tasks:
    - name: Pre-task | Update package cache
      tags: always
      apt:
        update_cache: true
        cache_valid_time: 3600
      changed_when: false

- hosts: all
  tags: base
  become: true
  roles:
    - base
