roles:
  - name: geerlingguy.docker
    version: "7.4.5"
  - name: staticdev.brave
    version: "1.3.2"
  - name: darkwizard242.vscode
    version: "1.5.0"
  - name: gantsign.oh-my-zsh
    version: "2.7.0"
