- name: Download Joplin installation script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh
    dest: /tmp/Joplin_install_and_update.sh
    mode: '0755'

- name: Run Joplin installation script
  ansible.builtin.command:
    cmd: /tmp/Joplin_install_and_update.sh
  become: false
  become_user: "{{ host_user }}"
