- name: Ensure ~/Applications directory exists
  file:
    path: "{{ base_appimage_dir }}"
    state: directory
    mode: "0755"
  become_user: "{{ user }}"

- name: Download and make AppImages executable
  with_items:
    - { name: "kMeet", url: "{{ base_appimage_kmeet_url }}" }
    - { name: "kChat", url: "{{ base_appimage_kchat_url }}" }
    - { name: "kDrive", url: "{{ base_appimage_kdrive_url }}" }
    - { name: "Nextcloud", url: "{{ base_appimage_nextcloud_url }}" }
    - { name: "LedgerLive", url: "{{ base_appimage_ledgerlive_url }}" }
  loop_control:
    label: "{{ item.name }}"
  get_url:
    url: "{{ item.url }}"
    dest: "{{ base_appimage_dir }}/{{ item.name }}.AppImage"
    mode: "0755"
  become_user: "{{ user }}"
