- name: Ensure ~/Applications directory exists
  file:
    path: "~/Applications"
    state: directory
    mode: "0755"

- name: Download and make AppImages executable
  with_items:
    - { name: "kMeet", url: "{{ base_appimage_kmeet_url }}" }
    - { name: "kChat", url: "{{ base_appimage_kchat_url }}" }
    - { name: "kDrive", url: "{{ base_appimage_kdrive_url }}" }
    - { name: "Nextcloud", url: "{{ base_appimage_nextcloud_url }}" }
  loop_control:
    label: "{{ item.name }}"
  get_url:
    url: "{{ item.url }}"
    dest: "~/Applications/{{ item.name }}.AppImage"
    mode: "0755"
