- name: Install base packages
  ansible.builtin.package:
    name:
      - bat
      - curl
      - fonts-powerline
      - gcc
      - git
      - htop
      - neovim
      - net-tools
      - rclone
      - ripgrep
      - sysstat
      - thunderbird
      - timewarrior
      - tree
      - unzip
      - wget
      - xclip
      - zsh
    state: present
