- name: Install Oh My Zsh # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    depth: 1

- name: Install timewarrior plugin
  ansible.builtin.git:
    repo: https://github.com/svenXY/timewarrior
    dest: ~/.oh-my-zsh/custom/plugins/timewarrior
    depth: 1

- name: Install zsh-autosuggestions plugin # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    depth: 1

- name: Install zsh-completions plugin # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-completions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-completions
    depth: 1

- name: Install zsh-syntax-highlighting plugin # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    depth: 1

- name: Install Oh My Zsh
  ansible.builtin.include_role:
    name: gantsign.oh-my-zsh
    apply:
      become: true
      become_user: root
  vars:
    oh_my_zsh_write_zshrc: true
    users:
      - username: "{{ user }}"
        oh_my_zsh:
          theme: robbyrussell
          plugins:
            - git
            - timewarrior
            - zsh-autosuggestions
            - zsh-completions
            - zsh-syntax-highlighting
          update_mode: auto
          update_frequency: 3

- name: Change user shell to zsh
  ansible.builtin.user:
    name: "{{ user }}"
    shell: /bin/zsh

