# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
    - ansible.builtin.import_tasks: software/base.yml
    - ansible.builtin.import_tasks: software/docker.yml
    - ansible.builtin.import_tasks: software/fonts.yml
    - ansible.builtin.import_tasks: software/zsh.yml
    - ansible.builtin.import_tasks: software/python.yml
