# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  # Software
    - name: Install base packages
      ansible.builtin.import_tasks: software/base.yml

    - name: Install Docker engine
      ansible.builtin.import_tasks: software/docker.yml

    - name: Install ZSH and plugins
      ansible.builtin.import_tasks: software/zsh.yml
      become_user: "{{ user }}"

    - name: Check actual Python version
      ansible.builtin.command:
        cmd: python --version
      register: python_version_raw

    - name: Extract Python version
      ansible.builtin.set_fact:
        python_version_actual: "{{ python_version_raw.stdout.split(' ')[1] }}"

    - name: Install requested Python version
      ansible.builtin.import_tasks: software/python.yml
      when: python_version_actual != python_version

  # Fonts
    - name: Install fonts
      ansible.builtin.import_tasks: fonts/fonts.yml
      become_user: "{{ user }}"

  # Configuration
    - name: Configure Git
      ansible.builtin.import_tasks: config/git.yml
      become_user: "{{ user }}"

    - name: Configure Neovim
      ansible.builtin.import_tasks: config/nvim.yml
      become_user: "{{ user }}"

